/**
 * Business Configuration - Single Source of Truth
 * This file is AUTO-GENERATED from business.yaml
 * Run `python generate_rules.py` to regenerate
 * DO NOT EDIT THIS FILE DIRECTLY - Edit business.yaml instead
 */

export interface ServiceItem {
  name: string;
  url: string;
  description?: string;
  subServices?: ServiceItem[];
}

export interface Location {
  city: string;
  state: string;
  url?: string;
}

export interface ContactInfo {
  address: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  areaCode: string;
  phone: string;
  email: string;
  addressVisibility: 'HIDDEN' | 'VISIBLE';
}

export interface SocialMedia {
  facebook?: string;
  twitter?: string;
  linkedin?: string;
  pinterest?: string;
  nextdoor?: string;
  yelp?: string;
  instagram?: string;
  youtube?: string;
}

export interface GoogleMaps {
  shortLink: string;
  fullUrl: string;
  embedCode: string;
  latitude: string;
  longitude: string;
}

export interface BusinessHours {
  monday: string;
  tuesday: string;
  wednesday: string;
  thursday: string;
  friday: string;
  saturday: string;
  sunday: string;
}

// ==========================================
// BUSINESS INFORMATION
// ==========================================
export const BUSINESS_INFO = {
  name: "Bujo Electric",
  websiteUrl: "https://bujoelectric.com",
  tone: "Professional",
  logoUrl: "/logo.webp",
  tagline: "Ekspertët tuaj për Energji dhe Siguri Elektrike",
  primaryKeyword: "Elektricist",
  ctaText: "Na kontaktoni sot për një konsultim falas!",
} as const;

// ==========================================
// BUSINESS CATEGORIES
// ==========================================
export const BUSINESS_CATEGORIES = {
  primary: "Electrician",
  secondary: [
    "Electrical Contractor",
    "Electrical Engineer",
    "Electrical Repair Shop",
    "Lighting Consultant",
    "Home Improvement"
  ],
} as const;

// ==========================================
// CORE SERVICES
// ==========================================
export const CORE_SERVICES: ServiceItem[] = [
  {
    name: "Instalime Elektrike",
    url: "/instalime-elektrike/",
    subServices: [
      { name: "Instalime Rezidenciale", url: "/instalime-elektrike-rezidenciale/" }
    ],
  },
  {
    name: "Riparime Elektrike",
    url: "/riparime-elektrike/",
    subServices: [
      { name: "Defekte Elektrike", url: "/defekte-elektrike/" },
      { name: "Ndërrim Siguresash & Panelev", url: "/nderrim-siguresash/" },
      { name: "Riparime Emergjente 24/7", url: "/riparime-emergjente/" }
    ],
  },
  {
    name: "Mirëmbajtje Elektrike",
    url: "/mirembajtje-elektrike/",
    subServices: [
      { name: "Kontroll & Inspektim", url: "/kontroll-inspektim/" },
      { name: "Mirëmbajtje Parandaluese", url: "/mirembajtje-parandaluese/" }
    ],
  },
  {
    name: "Ndriçim & Energji",
    url: "/ndricim-energji/",
    subServices: [
      { name: "Ndriçim LED", url: "/ndricim-led/" },
      { name: "Ndriçim i Jashtëm", url: "/ndricim-i-jashtem/" }
    ],
  },
  {
    name: "Sisteme Speciale",
    url: "/sisteme-elektrike/",
  }
];

// Flattened arrays for quick access
export const CORE_SERVICE_NAMES = CORE_SERVICES.map(s => s.name);
export const CORE_SERVICE_URLS = CORE_SERVICES.map(s => s.url);

// All services including sub-services
export const ALL_SERVICES = CORE_SERVICES.flatMap(service => [
  { name: service.name, url: service.url },
  ...(service.subServices || []),
]);

// ==========================================
// SERVICE AREAS / LOCATIONS
// ==========================================
export const LOCATIONS: Location[] = [
  { city: "Prishtinë", state: "Kosovë", url: "/prishtinë-kosovë/" },
  { city: "Prizren", state: "Kosovë", url: "/prizren-kosovë/" },
  { city: "Ferizaj", state: "Kosovë", url: "/ferizaj-kosovë/" },
  { city: "Gjilan", state: "Kosovë", url: "/gjilan-kosovë/" },
  { city: "Pejë", state: "Kosovë", url: "/pejë-kosovë/" },
  { city: "Gjakovë", state: "Kosovë", url: "/gjakovë-kosovë/" },
  { city: "Mitrovicë", state: "Kosovë", url: "/mitrovicë-kosovë/" },
  { city: "Fushë Kosovë", state: "Kosovë", url: "/fushë-kosovë-kosovë/" },
  { city: "Obiliq", state: "Kosovë", url: "/obiliq-kosovë/" },
  { city: "Podujevë", state: "Kosovë", url: "/podujevë-kosovë/" },
  { city: "Vushtrri", state: "Kosovë", url: "/vushtrri-kosovë/" },
  { city: "Lipjan", state: "Kosovë", url: "/lipjan-kosovë/" },
  { city: "Suharekë", state: "Kosovë", url: "/suharekë-kosovë/" }
];

// Helper to get top locations (first 4)
export const TOP_LOCATIONS = LOCATIONS.slice(0, 4);

// Helper to format location string
export const formatLocation = (location: Location): string => 
  `${location.city}, ${location.state}`;

// ==========================================
// CONTACT INFORMATION
// ==========================================
export const CONTACT: ContactInfo = {
  address: "Prishtinë, Kosovë",
  street: "Rruga Kryesore",
  city: "Prishtinë",
  state: "Kosovë",
  zip: "10000",
  areaCode: "044",
  phone: "044 239 757",
  email: "info@bujoelectric.com",
  addressVisibility: "VISIBLE", // SAB (Service Area Business)
};

// ==========================================
// BUSINESS HOURS
// ==========================================
export const BUSINESS_HOURS: BusinessHours = {
  monday: "24/7",
  tuesday: "24/7",
  wednesday: "24/7",
  thursday: "24/7",
  friday: "24/7",
  saturday: "24/7",
  sunday: "24/7",
};

// Helper to format business hours for schema
export const BUSINESS_HOURS_SCHEMA = "Mo-Fr 09:00-17:00";

// ==========================================
// GOOGLE MAPS
// ==========================================
export const GOOGLE_MAPS: GoogleMaps = {
  shortLink: "https://maps.app.goo.gl/bujoelectric",
  fullUrl: "https://www.google.com/maps/place/Bujo+Electric",
  embedCode: `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2934.6!2d21.1655!3d42.6629!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDLCsDM5JzQ2LjQiTiAyMcKwMDknNTUuOCJF!5e0!3m2!1sen!2s!4v1600000000000!5m2!1sen!2s" width="100%" height="300" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" class="w-full h-[300px] mb-4" title="Bujo Electric Map"></iframe>`,
  latitude: "42.6629",
  longitude: "21.1655",
};

// ==========================================
// SOCIAL MEDIA
// ==========================================
export const SOCIAL_MEDIA: SocialMedia = {
  facebook: "https://www.facebook.com/bujoelectric",
  instagram: "https://www.instagram.com/bujoelectric"
};

// Filter out undefined social media links
export const ACTIVE_SOCIAL_MEDIA = Object.entries(SOCIAL_MEDIA)
  .filter(([_, url]) => url)
  .reduce((acc, [key, url]) => ({ ...acc, [key]: url }), {}) as SocialMedia;

// ==========================================
// BLOG TOPICS
// ==========================================
export const BLOG_TOPICS = [
  "Këshilla për Sigurinë Elektrike",
  "Kursimi i Energjisë",
  "Mirëmbajtja e Shtëpisë",
  "Teknologjia Smart Home",
  "Zgjidhje për Biznese"
] as const;

// ==========================================
// META INFORMATION
// ==========================================
export const META = {
  title: "Bujo Electric | Ekspertët e Energjisë dhe Sigurisë Elektrike në Kosovë",
  description: "Shërbime elektrike profesionale 24/7 në Prishtinë dhe mbarë Kosovën. Instalime, riparime dhe mirëmbajtje elektrike me përvojë 15 vjeçare.",
  keywords: "elektricist, sherbime elektrike, prishtine, kosove, instalime elektrike, riparime elektrike, bujo electric",
} as const;

// ==========================================
// HELPER FUNCTIONS
// ==========================================

/**
 * Get services formatted for navigation/footer
 */
export const getServicesForNavigation = () => {
  return CORE_SERVICES.map(service => ({
    name: service.name,
    href: service.url,
  }));
};

/**
 * Get locations formatted for navigation/footer
 */
export const getLocationsForNavigation = (limit?: number) => {
  const locs = limit ? LOCATIONS.slice(0, limit) : LOCATIONS;
  return locs.map(location => ({
    name: formatLocation(location),
    href: location.url || `/${location.city.toLowerCase().replace(/\s+/g, '-')}-${location.state.toLowerCase()}/`,
  }));
};

/**
 * Get company links for footer/navigation
 */
export const getCompanyLinks = () => [
  { name: "Rreth Nesh", href: "/rreth-nesh/" },
  { name: "Blogu", href: "/blog/" },
  { name: "Kontakti", href: "/kontakti/" },
  { name: "Portofolio", href: "/galeria-e-projekteve/" },
  { name: "Zonat e Shërbimit", href: "/zonat-e-sherbimit/" },
];

/**
 * Get legal links for footer
 */
export const getLegalLinks = () => [
  { name: "Politika e Privatësisë", href: "/politika-e-privatesise/" },
  { name: "Kushtet e Përdorimit", href: "/kushtet-e-perdorimit/" },
];

/**
 * Format phone number for display (555-123-4567)
 */
export const formatPhoneDisplay = (phone: string): string => {
  const digits = phone.replace(/\D/g, '');
  if (digits.length === 10) {
    return `${digits.slice(0, 3)}-${digits.slice(3, 6)}-${digits.slice(6)}`;
  }
  if (digits.length === 11 && digits.startsWith('1')) {
    const withoutCountryCode = digits.slice(1);
    return `${withoutCountryCode.slice(0, 3)}-${withoutCountryCode.slice(3, 6)}-${withoutCountryCode.slice(6)}`;
  }
  return phone;
};

/**
 * Format phone number for tel: links (+15551234567)
 */
export const formatPhoneTel = (phone: string): string => {
  const digits = phone.replace(/\D/g, '');
  if (digits.length === 10) {
    return `+1${digits}`;
  }
  if (digits.length === 11 && digits.startsWith('1')) {
    return `+${digits}`;
  }
  if (phone.startsWith('+')) {
    return phone;
  }
  return `+1${digits}`;
};

export const getPhoneDisplay = (): string => formatPhoneDisplay(CONTACT.phone);
export const getPhoneTel = (): string => formatPhoneTel(CONTACT.phone);
export const getEmail = (): string => CONTACT.email;
export const getBusinessHours = (): BusinessHours => BUSINESS_HOURS;
export const getBusinessHoursForDay = (day: keyof BusinessHours): string => BUSINESS_HOURS[day];
export const getSocialLinks = (): SocialMedia => ACTIVE_SOCIAL_MEDIA;
export const getSocialLink = (platform: keyof SocialMedia): string | undefined => ACTIVE_SOCIAL_MEDIA[platform];
export const getAddress = (): string => CONTACT.address;
export const getCityState = (): string => `${CONTACT.city}, ${CONTACT.state}`;
export const getGoogleMapsLink = (): string => GOOGLE_MAPS.shortLink;
export const getGoogleMapsUrl = (): string => GOOGLE_MAPS.fullUrl;
export const getBusinessName = (): string => BUSINESS_INFO.name;
export const getTagline = (): string => BUSINESS_INFO.tagline;
export const getPrimaryKeyword = (): string => BUSINESS_INFO.primaryKeyword;
export const getWebsiteUrl = (): string => BUSINESS_INFO.websiteUrl;
export const getTopLocations = (count: number = 4): Location[] => LOCATIONS.slice(0, count);
export const getLocationsString = (limit?: number): string => {
  const locs = limit ? LOCATIONS.slice(0, limit) : LOCATIONS;
  return locs.map(loc => formatLocation(loc)).join(', ');
};
export const getPrimaryLocation = (): Location => LOCATIONS[0];
export const getServiceByName = (serviceName: string): ServiceItem | undefined => {
  return CORE_SERVICES.find(service => service.name === serviceName);
};
export const getServiceByUrl = (url: string): ServiceItem | undefined => {
  return CORE_SERVICES.find(service => service.url === url);
};
export const getSubServices = (serviceName: string): ServiceItem[] => {
  const service = getServiceByName(serviceName);
  return service?.subServices || [];
};
export const servesLocation = (city: string, state?: string): boolean => {
  if (state) {
    return LOCATIONS.some(loc => 
      loc.city.toLowerCase() === city.toLowerCase() && 
      loc.state.toLowerCase() === state.toLowerCase()
    );
  }
  return LOCATIONS.some(loc => loc.city.toLowerCase() === city.toLowerCase());
};
export const getMetaInfo = () => ({
  title: META.title,
  description: META.description,
  keywords: META.keywords,
});
export const getBlogTopics = (): readonly string[] => BLOG_TOPICS;
export const getCopyright = (): string => `© ${new Date().getFullYear()} ${BUSINESS_INFO.name}. Të gjitha të drejtat e rezervuara.`;
export const getBusinessCategories = () => BUSINESS_CATEGORIES;
export const getBusinessDescription = (): string => {
  return `Profesionistë në ${BUSINESS_INFO.primaryKeyword} që ofrojnë zgjidhje cilësore dhe shërbim të jashtëzakonshëm.`;
};
export const getContactInfo = () => ({
  phone: getPhoneDisplay(),
  email: getEmail(),
  address: getAddress(),
});
export const getSocialLinksFormatted = () => {
  return Object.entries(ACTIVE_SOCIAL_MEDIA).map(([key, href]) => ({
    name: key.charAt(0).toUpperCase() + key.slice(1),
    href: href as string,
    key: key as keyof SocialMedia,
  }));
};
export const getDefaultAddresses = () => [
  {
    location: getCityState(),
    address: getAddress(),
  }
];
export const getDefaultMapLocation = () => ({
  id: "main-location",
  name: getCityState(),
  address: getAddress(),
  mapEmbed: GOOGLE_MAPS.embedCode.match(/src="([^"]*)"/)?.[1] || "",
  mapTitle: `${getBusinessName()} ${getCityState()} Location`,
  isMain: true as const,
});
