/**
 * Business Configuration - Single Source of Truth
 * This file is AUTO-GENERATED from business.yaml
 * Run `python generate_rules.py` to regenerate
 * DO NOT EDIT THIS FILE DIRECTLY - Edit business.yaml instead
 */

export interface ServiceItem {
  name: string;
  url: string;
  description?: string;
  subServices?: ServiceItem[];
}

export interface Location {
  city: string;
  state: string;
  url?: string;
}

export interface ContactInfo {
  address: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  areaCode: string;
  phone: string;
  email: string;
  addressVisibility: 'HIDDEN' | 'VISIBLE';
}

export interface SocialMedia {
  facebook?: string;
  twitter?: string;
  linkedin?: string;
  pinterest?: string;
  nextdoor?: string;
  yelp?: string;
  instagram?: string;
  youtube?: string;
}

export interface GoogleMaps {
  shortLink: string;
  fullUrl: string;
  embedCode: string;
  latitude: string;
  longitude: string;
}

export interface BusinessHours {
  monday: string;
  tuesday: string;
  wednesday: string;
  thursday: string;
  friday: string;
  saturday: string;
  sunday: string;
}

// ==========================================
// BUSINESS INFORMATION
// ==========================================
export const BUSINESS_INFO = {
  name: "Example Company",
  websiteUrl: "https://example.com",
  tone: "Professional",
  logoUrl: "https://example.com/logo.png",
  tagline: "Your Trusted Service Provider",
  primaryKeyword: "Professional Services",
  ctaText: "Contact us today for a free consultation!",
} as const;

// ==========================================
// BUSINESS CATEGORIES
// ==========================================
export const BUSINESS_CATEGORIES = {
  primary: "Service Provider",
  secondary: [
    "Professional Services",
    "Local Business",
    "Service Establishment",
    "Contractor",
    "Home Services"
  ],
} as const;

// ==========================================
// SCHEMA.ORG BUSINESS TYPE
// ==========================================
// The Schema.org type that best describes this business
// Used for structured data markup on the website
export const SCHEMA_BUSINESS_TYPE = "ProfessionalService" as const;

// ==========================================
// CORE SERVICES
// ==========================================
export const CORE_SERVICES: ServiceItem[] = [
  {
    name: "Service One",
    url: "/service-one/",
    subServices: [
      { name: "Residential Service One", url: "/residential-service-one/" },
      { name: "Commercial Service One", url: "/commercial-service-one/" },
      { name: "Custom Service One", url: "/custom-service-one/" }
    ],
  },
  {
    name: "Service Two",
    url: "/service-two/",
    subServices: [
      { name: "Emergency Service Two", url: "/emergency-service-two/" },
      { name: "Standard Service Two", url: "/standard-service-two/" },
      { name: "Premium Service Two", url: "/premium-service-two/" }
    ],
  },
  {
    name: "Service Three",
    url: "/service-three/",
    subServices: [
      { name: "Basic Service Three", url: "/basic-service-three/" },
      { name: "Advanced Service Three", url: "/advanced-service-three/" },
      { name: "Maintenance Plans", url: "/maintenance-plans/" }
    ],
  },
  {
    name: "Service Four",
    url: "/service-four/",
    subServices: [
      { name: "Installation", url: "/installation/" },
      { name: "Repair", url: "/repair/" },
      { name: "Smart Solutions", url: "/smart-solutions/" }
    ],
  },
  {
    name: "Service Five",
    url: "/service-five/",
    subServices: [
      { name: "Option A", url: "/option-a/" },
      { name: "Option B", url: "/option-b/" },
      { name: "Option C", url: "/option-c/" },
      { name: "Option D", url: "/option-d/" }
    ],
  }
];

// Flattened arrays for quick access
export const CORE_SERVICE_NAMES = CORE_SERVICES.map(s => s.name);
export const CORE_SERVICE_URLS = CORE_SERVICES.map(s => s.url);

// All services including sub-services
export const ALL_SERVICES = CORE_SERVICES.flatMap(service => [
  { name: service.name, url: service.url },
  ...(service.subServices || []),
]);

// ==========================================
// SERVICE AREAS / LOCATIONS
// ==========================================
export const LOCATIONS: Location[] = [
  { city: "Example City", state: "ST", url: "/example-city-st/" },
  { city: "North Town", state: "ST", url: "/north-town-st/" },
  { city: "South Town", state: "ST", url: "/south-town-st/" },
  { city: "East Village", state: "ST", url: "/east-village-st/" },
  { city: "West Borough", state: "ST", url: "/west-borough-st/" },
  { city: "Central District", state: "ST", url: "/central-district-st/" },
  { city: "Riverside", state: "ST", url: "/riverside-st/" },
  { city: "Hillside", state: "ST", url: "/hillside-st/" },
  { city: "Lakeside", state: "ST", url: "/lakeside-st/" },
  { city: "Mountain View", state: "ST", url: "/mountain-view-st/" },
  { city: "Valley Springs", state: "ST", url: "/valley-springs-st/" },
  { city: "Meadowbrook", state: "ST", url: "/meadowbrook-st/" },
  { city: "Oak Grove", state: "ST", url: "/oak-grove-st/" },
  { city: "Pine Hills", state: "ST", url: "/pine-hills-st/" },
  { city: "Maple Ridge", state: "ST", url: "/maple-ridge-st/" }
];

// Helper to get top locations (first 4)
export const TOP_LOCATIONS = LOCATIONS.slice(0, 4);

// Helper to format location string
export const formatLocation = (location: Location): string => 
  `${location.city}, ${location.state}`;

// ==========================================
// CONTACT INFORMATION
// ==========================================
export const CONTACT: ContactInfo = {
  address: "123 Main Street, Example City, ST 12345",
  street: "123 Main Street",
  city: "Example City",
  state: "ST",
  zip: "12345",
  areaCode: "555",
  phone: "(555) 123-4567",
  email: "info@example.com",
  addressVisibility: "VISIBLE", // SAB (Service Area Business)
};

// ==========================================
// BUSINESS HOURS
// ==========================================
export const BUSINESS_HOURS: BusinessHours = {
  monday: "9:00 AM - 5:00 PM",
  tuesday: "9:00 AM - 5:00 PM",
  wednesday: "9:00 AM - 5:00 PM",
  thursday: "9:00 AM - 5:00 PM",
  friday: "9:00 AM - 5:00 PM",
  saturday: "10:00 AM - 3:00 PM",
  sunday: "Closed",
};

// Helper to format business hours for schema
export const BUSINESS_HOURS_SCHEMA = "Mo-Fr 09:00-17:00";

// ==========================================
// GOOGLE MAPS
// ==========================================
export const GOOGLE_MAPS: GoogleMaps = {
  shortLink: "https://maps.app.goo.gl/example",
  fullUrl: "https://www.google.com/maps/place/Example+Company",
  embedCode: `<iframe src="https://www.google.com/maps/embed?pb=EXAMPLE_EMBED_CODE" width="100%" height="300" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" class="w-full h-[300px] mb-4" title="Example Company Map"></iframe>`,
  latitude: "40.7128",
  longitude: "-74.0060",
};

// ==========================================
// SOCIAL MEDIA
// ==========================================
export const SOCIAL_MEDIA: SocialMedia = {
  facebook: "https://www.facebook.com/examplecompany",
  twitter: "https://twitter.com/examplecompany",
  linkedin: "https://www.linkedin.com/company/examplecompany",
  instagram: "https://www.instagram.com/examplecompany"
};

// Filter out undefined social media links
export const ACTIVE_SOCIAL_MEDIA = Object.entries(SOCIAL_MEDIA)
  .filter(([, url]) => url)
  .reduce((acc, [key, url]) => ({ ...acc, [key]: url }), {}) as SocialMedia;

// ==========================================
// BLOG TOPICS
// ==========================================
export const BLOG_TOPICS = [
  "Industry Tips and Tricks",
  "Best Practices Guide",
  "How to Choose the Right Solution",
  "Common Problems and Solutions",
  "Latest Technology Trends"
] as const;

// ==========================================
// META INFORMATION
// ==========================================
export const META = {
  title: "Example Company - Professional Services in Example City, ST",
  description: "Expert professional services in Example City, ST. Quality solutions and customer satisfaction guaranteed. Contact us today for a free consultation!",
  keywords: "professional services, Example City ST, quality service, reliable solutions, expert services",
} as const;

// ==========================================
// HELPER FUNCTIONS
// ==========================================

/**
 * Get services formatted for navigation/footer
 */
export const getServicesForNavigation = () => {
  return CORE_SERVICES.map(service => ({
    name: service.name,
    href: service.url,
  }));
};

/**
 * Get locations formatted for navigation/footer
 */
export const getLocationsForNavigation = (limit?: number) => {
  const locs = limit ? LOCATIONS.slice(0, limit) : LOCATIONS;
  return locs.map(location => ({
    name: formatLocation(location),
    href: location.url || `/${location.city.toLowerCase().replace(/\s+/g, '-')}-${location.state.toLowerCase()}/`,
  }));
};

/**
 * Get company links for footer/navigation
 */
export const getCompanyLinks = () => [
  { name: "About Us", href: "/about/" },
  { name: "Blog", href: "/blog/" },
  { name: "Contact", href: "/contact/" },
  { name: "Portfolio", href: "/portfolio/" },
  { name: "Service Areas", href: "/service-areas/" },
];

/**
 * Get legal links for footer
 */
export const getLegalLinks = () => [
  { name: "Privacy Policy", href: "/privacy-policy/" },
  { name: "Terms & Conditions", href: "/terms/" },
];

/**
 * Format phone number for display (555-123-4567)
 */
export const formatPhoneDisplay = (phone: string): string => {
  const digits = phone.replace(/\D/g, '');
  if (digits.length === 10) {
    return `${digits.slice(0, 3)}-${digits.slice(3, 6)}-${digits.slice(6)}`;
  }
  if (digits.length === 11 && digits.startsWith('1')) {
    const withoutCountryCode = digits.slice(1);
    return `${withoutCountryCode.slice(0, 3)}-${withoutCountryCode.slice(3, 6)}-${withoutCountryCode.slice(6)}`;
  }
  return phone;
};

/**
 * Format phone number for tel: links (+15551234567)
 */
export const formatPhoneTel = (phone: string): string => {
  const digits = phone.replace(/\D/g, '');
  if (digits.length === 10) {
    return `+1${digits}`;
  }
  if (digits.length === 11 && digits.startsWith('1')) {
    return `+${digits}`;
  }
  if (phone.startsWith('+')) {
    return phone;
  }
  return `+1${digits}`;
};

export const getPhoneDisplay = (): string => formatPhoneDisplay(CONTACT.phone);
export const getPhoneTel = (): string => formatPhoneTel(CONTACT.phone);
export const getEmail = (): string => CONTACT.email;
export const getBusinessHours = (): BusinessHours => BUSINESS_HOURS;
export const getBusinessHoursForDay = (day: keyof BusinessHours): string => BUSINESS_HOURS[day];
export const getSocialLinks = (): SocialMedia => ACTIVE_SOCIAL_MEDIA;
export const getSocialLink = (platform: keyof SocialMedia): string | undefined => ACTIVE_SOCIAL_MEDIA[platform];
export const getAddress = (): string => CONTACT.address;
export const getCityState = (): string => `${CONTACT.city}, ${CONTACT.state}`;
export const getGoogleMapsLink = (): string => GOOGLE_MAPS.shortLink;
export const getGoogleMapsUrl = (): string => GOOGLE_MAPS.fullUrl;
export const getBusinessName = (): string => BUSINESS_INFO.name;
export const getTagline = (): string => BUSINESS_INFO.tagline;
export const getPrimaryKeyword = (): string => BUSINESS_INFO.primaryKeyword;
export const getWebsiteUrl = (): string => BUSINESS_INFO.websiteUrl;
export const getTopLocations = (count: number = 4): Location[] => LOCATIONS.slice(0, count);
export const getLocationsString = (limit?: number): string => {
  const locs = limit ? LOCATIONS.slice(0, limit) : LOCATIONS;
  return locs.map(loc => formatLocation(loc)).join(', ');
};
export const getPrimaryLocation = (): Location => LOCATIONS[0];
export const getServiceByName = (serviceName: string): ServiceItem | undefined => {
  return CORE_SERVICES.find(service => service.name === serviceName);
};
export const getServiceByUrl = (url: string): ServiceItem | undefined => {
  return CORE_SERVICES.find(service => service.url === url);
};
export const getSubServices = (serviceName: string): ServiceItem[] => {
  const service = getServiceByName(serviceName);
  return service?.subServices || [];
};
export const servesLocation = (city: string, state?: string): boolean => {
  if (state) {
    return LOCATIONS.some(loc => 
      loc.city.toLowerCase() === city.toLowerCase() && 
      loc.state.toLowerCase() === state.toLowerCase()
    );
  }
  return LOCATIONS.some(loc => loc.city.toLowerCase() === city.toLowerCase());
};
export const getMetaInfo = () => ({
  title: META.title,
  description: META.description,
  keywords: META.keywords,
});
export const getBlogTopics = (): readonly string[] => BLOG_TOPICS;
export const getCopyright = (): string => `© ${new Date().getFullYear()} ${BUSINESS_INFO.name}. All rights reserved.`;
export const getBusinessCategories = () => BUSINESS_CATEGORIES;
export const getBusinessDescription = (): string => {
  return `Professional ${BUSINESS_INFO.primaryKeyword} providing quality solutions and exceptional customer service.`;
};
export const getContactInfo = () => ({
  phone: getPhoneDisplay(),
  email: getEmail(),
  address: getAddress(),
});
export const getSocialLinksFormatted = () => {
  return Object.entries(ACTIVE_SOCIAL_MEDIA).map(([key, href]) => ({
    name: key.charAt(0).toUpperCase() + key.slice(1),
    href: href as string,
    key: key as keyof SocialMedia,
  }));
};
export const getDefaultAddresses = () => [
  {
    location: getCityState(),
    address: getAddress(),
  }
];
export const getDefaultMapLocation = () => ({
  id: "main-location",
  name: getCityState(),
  address: getAddress(),
  mapEmbed: GOOGLE_MAPS.embedCode.match(/src="([^"]*)"/)?.[1] || "",
  mapTitle: `${getBusinessName()} ${getCityState()} Location`,
  isMain: true as const,
});
